recover_erecover:
    resource: "@RecoverErecoverBundle/Resources/config/routing.yml"
    prefix:   /recover

myAppFilmothequeBundle:
    resource: "@MyAppFilmothequeBundle/Resources/config/routing.yml"
    prefix:   /myapp

ens_jobeet:
    resource: "@EnsJobeetBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    pattern: /login
    defaults: { _controller: RecoverUserBundle:Security:login }
    
login_check:
    pattern: /login_check
logout:
    pattern: /logout
