recover_erecover:
    resource: "@RecoverErecoverBundle/Resources/config/routing.yml"
    prefix:   /recover

myAppFilmothequeBundle:
    resource: "@MyAppFilmothequeBundle/Resources/config/routing.yml"
    prefix:   /myapp

ens_jobeet:
    resource: "@EnsJobeetBundle/Resources/config/routing.yml"
    prefix:   /

