jms_security_extra: 
    secure_all_services: false 
    expressions: true
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Recover\UserBundle\Entity\User
    group:
        group_class : Recover\UserBundle\Entity\Groupe
    service: 
        mailer: fos_user.mailer.twig_swift
    #resetting:
    #    email:
    #        template: RecoverUserBundle:User:registration.email.twi
    from_email:
        address:        webmaster@example.com
        sender_name:    Admin
    
    profile:
        form:
            type:               fos_user_profile
            #handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Profile]
    change_password:
        form:
            type:               fos_user_change_password
            #handler:            fos_user.change_password.form.handler.default
            name:               fos_user_change_password_form
            validation_groups:  [ChangePassword]
        
    registration:
        #form:
            #type: recover_userbundle_user  
        confirmation:
            enabled: true
            from_email: 
                address: absbs-technologies@outlook.fr
                sender_name: ABSBS Technologies
            template: RecoverUserBundle:User:registration.email.twig
        form:
            type:               fos_user_registration
            #handler:            fos_user.registration.form.handler.default
            name:               fos_user_registration_form
            validation_groups:  [Registration]
        
        
security:
    encoders:
        Recover\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER,ROLE_AGENT,ROLE_SOCIETE]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
             id: fos_user.user_provider.username
             
        
    firewalls:
        main:
            pattern: ^/
            anonymous: true 
            provider: main
            form_login:
                  login_path: fos_user_security_login
                  check_path: fos_user_security_check
            logout:
                  path: fos_user_security_logout 
                  target: /recover
            remember_me:
                  key: %secret%

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/recover, roles: [ROLE_USER,ROLE_AGENT,ROLE_SOCIETE] }